[package]
name = "rust_rocket"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
handlebars = "4.3.7"
rocket = "=0.5.0-rc.3"
tera = "1.19.0"

[dependencies.rocket_dyn_templates]
version = "=0.1.0-rc.3"
features = ["handlebars", "tera"]
